ignore:
  - '\.pathogen\.yml$'
variables:
  - name: module
    description: the go module of the server (e.g., github.com/galaho/pathogen)
  - name: name
    description: the name of the server
  - name: description
    description: the description of the server
  - name: author
    description: the author of the server
scripts:
